#!/bin/sh
set -eu

tool=$(basename "$0")

if test "$tool" = "contai"
then
	tool=
fi

data_dir=~/.local/share/contai

home_dir=$data_dir/home

mkdir -p "$home_dir"

docker run \
	--rm \
	-it \
	--user $(id -un):$(id -gn) \
	-v "$home_dir:$HOME" \
	-v "$PWD:$PWD" \
	-w "$PWD" \
	contai:latest \
	$tool \
	"$@"
